Use 0.19 release of toml_edit
DevinR528/cargo-sort pull request #59
Opened 2023-02-14 22:09 UTC by matze

Finally had the time and essentially port #29 to toml_edit 0.19. All tests pass, so there's that.

2023-02-14 22:38 UTC, matze commented
Not sure about the Windows failure. I would actually expect no `\r` to exist unlike what the test asserts.

2023-02-15 23:58 UTC, DevinR528 requested changes
The `fixtures/` folder and all things within are junk, they were only for `toml_edit` tests you can leave that as a separate commit if that works.

Thanks again!

2023-02-15 23:58 UTC, DevinR528 commented on src/fmt.rs
>      #[cfg(target_os = "windows")]
Sorry github won't let me click on line 305 should be
```
"[package]\nname = \"priv-test\"\nversion = \"0.1.0\"\nedition = \"2021\"\nresolver = \"2\"\n# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\n\n[dependencies]\nstructopt = \"0.3\"\n"
```

(Remove the `\r` as you suggested)

2023-02-15 23:58 UTC, DevinR528 commented on src/fmt.rs
>  ///
line 57 above the doc comments for `pub crlf: bool` could you add
```
// NOTE: this is only used in main, fmt doesn't set the line endings
```
(I forget this every time I look through this code base) Thanks.

2023-02-16 08:04 UTC, matze commented
I added your commits, thanks for having a look on Windows as well :-)

2023-04-07 11:21 UTC, SimenB commented
Ping 😀

2024-10-19 18:25 UTC, jplatte commented
An upgrade was merged in #29, I'll upgrade again now.

2024-10-19 18:25 UTC, closed without merging